In [16]:
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
import make_folder as mkf
import numpy as np
import os
import pandas 

label_map = {action:num for num,action in enumerate(mkf.actions)}
print(label_map)

{'Hello': 0, 'Thanks': 1, 'ILoveYou': 2}


In [17]:
sequences, labels = [], []
for action in mkf.actions:
    for sequence in np.array(os.listdir(os.path.join(mkf.DATA_PATH, action))).astype(int):
        window = []
        for frame_num in range(mkf.sequence_length):
            res = np.load(os.path.join(mkf.DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [18]:
np.array(sequences).shape
np.array(labels).shape
x = np.array(sequences)
y = to_categorical(labels, dtype ="uint8")
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1)
print(X_train.shape,X_test.shape,y)

(81, 30, 1662) (9, 30, 1662) [[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [30]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.callbacks import TensorBoard

log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

model = Sequential()
model.add(LSTM(64, return_sequences=True, activation='relu', input_shape=(30,1662)))
model.add(LSTM(64, return_sequences=False, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(mkf.actions.shape[0], activation='softmax'))

model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])
model.fit(X_train, y_train, epochs=300, callbacks=[tb_callback])


Epoch 1/300
3/3 [==============================] - 1s 29ms/step - loss: 2.4585 - categorical_accuracy: 0.3827
Epoch 2/300
3/3 [==============================] - 0s 29ms/step - loss: 2.7139 - categorical_accuracy: 0.3704
Epoch 3/300
3/3 [==============================] - 0s 29ms/step - loss: 1.3625 - categorical_accuracy: 0.4815
Epoch 4/300
3/3 [==============================] - 0s 28ms/step - loss: 1.2643 - categorical_accuracy: 0.3210
Epoch 5/300
3/3 [==============================] - 0s 27ms/step - loss: 1.3856 - categorical_accuracy: 0.3333
Epoch 6/300
3/3 [==============================] - 0s 29ms/step - loss: 1.1584 - categorical_accuracy: 0.3333
Epoch 7/300
3/3 [==============================] - 0s 28ms/step - loss: 1.0068 - categorical_accuracy: 0.5309
Epoch 8/300
3/3 [==============================] - 0s 28ms/step - loss: 0.9999 - categorical_accuracy: 0.5062
Epoch 9/300
3/3 [==============================] - 0s 27ms/step - loss: 0.9739 - categorical_accuracy: 0.4691
Epoch 10/3

3/3 [==============================] - 0s 29ms/step - loss: 0.1383 - categorical_accuracy: 0.9630
Epoch 75/300
3/3 [==============================] - 0s 28ms/step - loss: 0.1335 - categorical_accuracy: 0.9630
Epoch 76/300
3/3 [==============================] - 0s 28ms/step - loss: 0.1178 - categorical_accuracy: 0.9630
Epoch 77/300
3/3 [==============================] - 0s 29ms/step - loss: 0.1240 - categorical_accuracy: 0.9630
Epoch 78/300
3/3 [==============================] - 0s 28ms/step - loss: 0.1081 - categorical_accuracy: 0.9630
Epoch 79/300
3/3 [==============================] - 0s 27ms/step - loss: 0.0812 - categorical_accuracy: 0.9630
Epoch 80/300
3/3 [==============================] - 0s 28ms/step - loss: 0.0713 - categorical_accuracy: 0.9630
Epoch 81/300
3/3 [==============================] - 0s 28ms/step - loss: 0.0809 - categorical_accuracy: 0.9506
Epoch 82/300
3/3 [==============================] - 0s 28ms/step - loss: 0.0736 - categorical_accuracy: 0.9630
Epoch 83/300
3

3/3 [==============================] - 0s 36ms/step - loss: 0.1156 - categorical_accuracy: 0.9630
Epoch 148/300
3/3 [==============================] - 0s 38ms/step - loss: 0.0929 - categorical_accuracy: 0.9506
Epoch 149/300
3/3 [==============================] - 0s 37ms/step - loss: 0.1039 - categorical_accuracy: 0.9506
Epoch 150/300
3/3 [==============================] - 0s 38ms/step - loss: 0.0742 - categorical_accuracy: 0.9630
Epoch 151/300
3/3 [==============================] - 0s 41ms/step - loss: 0.0773 - categorical_accuracy: 0.9630
Epoch 152/300
3/3 [==============================] - 0s 36ms/step - loss: 0.0856 - categorical_accuracy: 0.9630
Epoch 153/300
3/3 [==============================] - 0s 36ms/step - loss: 0.0586 - categorical_accuracy: 0.9753
Epoch 154/300
3/3 [==============================] - 0s 40ms/step - loss: 0.0638 - categorical_accuracy: 0.9753
Epoch 155/300
3/3 [==============================] - 0s 40ms/step - loss: 1.3964 - categorical_accuracy: 0.7531
Epoch 

3/3 [==============================] - 0s 42ms/step - loss: 0.0071 - categorical_accuracy: 1.0000
Epoch 221/300
3/3 [==============================] - 0s 39ms/step - loss: 0.0058 - categorical_accuracy: 1.0000
Epoch 222/300
3/3 [==============================] - 0s 35ms/step - loss: 0.0074 - categorical_accuracy: 1.0000
Epoch 223/300
3/3 [==============================] - 0s 39ms/step - loss: 0.0054 - categorical_accuracy: 1.0000
Epoch 224/300
3/3 [==============================] - 0s 39ms/step - loss: 0.0053 - categorical_accuracy: 1.0000
Epoch 225/300
3/3 [==============================] - 0s 40ms/step - loss: 0.0045 - categorical_accuracy: 1.0000
Epoch 226/300
3/3 [==============================] - 0s 39ms/step - loss: 0.0031 - categorical_accuracy: 1.0000
Epoch 227/300
3/3 [==============================] - 0s 36ms/step - loss: 0.0042 - categorical_accuracy: 1.0000
Epoch 228/300
3/3 [==============================] - 0s 38ms/step - loss: 0.0023 - categorical_accuracy: 1.0000
Epoch 

3/3 [==============================] - 0s 41ms/step - loss: 1.2503e-04 - categorical_accuracy: 1.0000
Epoch 292/300
3/3 [==============================] - 0s 41ms/step - loss: 1.1920e-04 - categorical_accuracy: 1.0000
Epoch 293/300
3/3 [==============================] - 0s 39ms/step - loss: 1.1446e-04 - categorical_accuracy: 1.0000
Epoch 294/300
3/3 [==============================] - 0s 39ms/step - loss: 1.0909e-04 - categorical_accuracy: 1.0000
Epoch 295/300
3/3 [==============================] - 0s 40ms/step - loss: 1.0609e-04 - categorical_accuracy: 1.0000
Epoch 296/300
3/3 [==============================] - 0s 38ms/step - loss: 1.0260e-04 - categorical_accuracy: 1.0000
Epoch 297/300
3/3 [==============================] - 0s 41ms/step - loss: 9.8779e-05 - categorical_accuracy: 1.0000
Epoch 298/300
3/3 [==============================] - 0s 40ms/step - loss: 9.3511e-05 - categorical_accuracy: 1.0000
Epoch 299/300
3/3 [==============================] - 0s 41ms/step - loss: 9.0430e-05 -

In [32]:
import joblib

# Train your machine learning model

# Save the model to a file
joblib.dump(model, 'signLanguageModel.pkl')

INFO:tensorflow:Assets written to: ram://e38e5f1e-1336-44e5-b86a-de542faf6b5f/assets


['signLanguageModel.pkl']

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 30, 64)            442112    
                                                                 
 lstm_1 (LSTM)               (None, 64)                33024     
                                                                 
 dense (Dense)               (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 3)                 99        
                                                                 
Total params: 477,315
Trainable params: 477,315
Non-trainable params: 0
_________________________________________________________________


In [6]:

res = model.predict(X_test)
model.save('action.h5')
model.load_weights('action.h5')

1/1 [==============================] - 0s 306ms/step


In [31]:
import cv2 as cv
import holistic_tracking.holisticTrackingModule as htm

detector = htm.holisticDetector()
vid = cv.VideoCapture(0)
input_frames = []     #input frames from camera consisting of 30 frames each     
predictions = []

while True:
    isTrue, img = vid.read()
    img = cv.flip(img, 1)
    img, results = detector.find_body(img)
    keypoints = detector.extract_keypoints(results)
    input_frames.append(keypoints)
    
    if len(input_frames) == 30:
        cv.waitKey(1000)
        res = model.predict(np.expand_dims(input_frames, axis=0))[0]
        print(mkf.actions[np.argmax(res)])
        predictions.append(mkf.actions[np.argmax(res)])
        input_frames = []
    if predictions:
        prediction_text = " ".join(predictions[-1])
    else:
        prediction_text = " "
    cv.putText(img, f'The word you said is {prediction_text}', (10,200), cv.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv.LINE_AA)
    cv.imshow('OpenCV Feed', img)

    if cv.waitKey(10) & 0xFF == ord("q"):   #press q to close video
        break

vid.release()
cv.destroyAllWindows()

1/1 [==============================] - 0s 205ms/step
Hello
1/1 [==============================] - 0s 15ms/step
Hello
1/1 [==============================] - 0s 15ms/step
Hello
1/1 [==============================] - 0s 14ms/step
Hello
1/1 [==============================] - 0s 13ms/step
Thanks
1/1 [==============================] - 0s 14ms/step
Hello
1/1 [==============================] - 0s 14ms/step
Thanks
1/1 [==============================] - 0s 14ms/step
Thanks
1/1 [==============================] - 0s 15ms/step
Thanks
1/1 [==============================] - 0s 14ms/step
ILoveYou
1/1 [==============================] - 0s 14ms/step
ILoveYou
1/1 [==============================] - 0s 14ms/step
ILoveYou
1/1 [==============================] - 0s 13ms/step
Thanks
1/1 [==============================] - 0s 14ms/step
ILoveYou
1/1 [==============================] - 0s 14ms/step
ILoveYou
1/1 [==============================] - 0s 14ms/step
Hello
1/1 [==============================] - 0s 14ms/step